production:
  adapter: mysql2
  database: pets
  host: localhost
  username: root
  password: root
  port: 3306
  encoding: utf8

development:
  adapter: mysql2
  database: pets
  server: localhost
  host: localhost
  username: root
  password: root
  port: 3306
  encoding: utf8
